### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ribeiro-rodrigo** [globocom/enforcement-service#15]
This issue describes a way to improve the error handling of the enforement operator.

The following situations need to be addressed:

- Invalid enforcement
- Connection error with the cluster source
- Connection error with ArgoCD

When an attempt is made to create or update an invalid enforcement, it must be listed in the status of the custom resource.

See an example of the status

```yaml
Status:
  Create:
    Clusters:
      Name:  cluster1
      URL:   https://192.168.0.76/k8s/clusters/c-cx9wq
    install_errors:
      helm-guestbook
  Kopf:
    Progress:
  Sync:
    Clusters:
      Name:  cluster1
      URL:   https://192.168.0.76/k8s/clusters/c-cx9wq
  update/spec.enforcements:
    install_errors:
    update_errors:

```

The operator should also not allow the sync controller to start if the create has ended in error.

**Comment by ribeiro-rodrigo** [comment]
The status of the custom resource has been grouped within a single field. All controllers obtain and change the status of that field.

```yaml
Status:
  sync/spec.enforcements:
    Clusters:
      Name:  cluster1
      URL:   https://192.168.0.76/k8s/clusters/c-cx9wq
   install_errors:
       - enforcement1
       - enforcement2
```
Grouping makes debugging easier
