### ISSUE TITLE
Trigger BeforeInstall and AfterInstall

### ISSUE THREAD

**Issue by ribeiro-rodrigo** [globocom/enforcement-service#32]
The application must allow the configuration of triggers that must be activated before and after each package installation performed. The triggers must be HTTP requests of the Post type, where information about the cluster that is receiving the installation and the respective package must be passed.

Below is an example of a cluster rule with a configured trigger. 

```yaml
apiVersion: enforcement.globo.com/v1beta1
kind: ClusterRule
metadata:
  name: dev-rules
spec:
  enforcements:
    ...
  source:
    secretName: rancher-secret
    rancher: {}
  triggers:
    beforeInstall: 
      endpoint: http://localhost:8080/before
      timeout: 5 # in seconds 
    afterInstall:
      endpoint: http://localhost:8080/after
      timeout: 15 # in seconds   
      
      ...
```
In the absence of a timeout setting, the default should be 5 seconds.
