### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by ribeiro-rodrigo** [globocom/enforcement-service#33]
Enforcement must allow dynamic values ​​in the configuration of cluster rules.
It should be possible to specify in the configuration of the cluster rule, cluster information returned by the cluster source through a simple expression language.

Example:

```yaml
apiVersion: enforcement.globo.com/v1beta1
kind: ClusterRule
metadata:
  name: dev-rules
spec:
  enforcements:
    - name: helm-guestbook
      repo: https://github.com/argoproj/argocd-example-apps
      path: "${cluster_name}/helm-guestbook"
      helm:
        parameters:
          replicaCount: 1
          cluster: ${cluster_name}

  source:
    rancher: {}
```
Dynamic configuration should only be allowed within the enforcement field
